### Preprocesamiento Data Mussel

In [1]:
import os
import pandas as pd
import numpy as np
from openpyxl import load_workbook
import re
import pyexcel as p

# 2021

In [4]:
# Setear directorios.
current = os.chdir('/Users/erossel/Dropbox/Salmon Derivates/Datamussel/Data mensual y semanal/')
prices = '/Users/erossel/Dropbox/Salmon Derivates/Datamussel/Data mensual y semanal/Indice Precios DataMussel/'
year = 2020
weeks = os.listdir('/Users/erossel/Dropbox/Salmon Derivates/Datamussel/Data mensual y semanal/Indice Precios DataMussel/'+str(year))

### CAMANCHACA

In [694]:
#Camanchaca
camanchaca = pd.DataFrame()

for w in weeks:
    try:
        os.chdir(prices+str(year)+'/'+str(w))
    except:
        print('Error al ingresar a', w)
        continue
    w_files = os.listdir(prices+str(year)+'/'+str(w)+'/')
    for file in w_files:
        if 'camanchaca' in file.lower():
            print(file)
            if file[-4:] != '.lnk':
                # Casos XLS
                if file[-4:] in ['.xls','.slk'] :
                    try:
                        df = pd.read_excel(prices+str(year)+'/'+str(w)+'/'+file)
                        #Anexar
                        camanchaca = camanchaca.append(df)
                        
                    except:
                        print('Error en', file)
                else: # Casos XLSX
                    try: 
                        #Leer hoja donde est√° la tabla
                        wb = load_workbook(filename = prices+str(year)+'/'+str(w)+'/'+file)
                        hoja = wb.sheetnames
                        sheet = wb[hoja[0]]

                        #Transformar hoja en un df
                        df = pd.DataFrame(sheet.values) 

                        #Limitar el df
                        df.reset_index(inplace = True, drop=True)

                        #Anexar
                        camanchaca = camanchaca.append(df)
                    except:
                        print('Error en', file)

DM Camanchaca 2020_10a14.xlsx
DM Camanchaca 2020_1_17.xlsx
DM Camanchaca 2020_18 y 19.xlsx
DM Camanchaca 2020_18 y 19.xlsx
DataMussel 2 Camanchaca.xlsx
DM Camanchaca 2020_20.xlsx
DM Camanchaca 2020_21.xlsx
DM Camanchaca 2020_22.xlsx
DM Camanchaca 2020_23.xlsx
DM Camanchaca 2020_24.xlsx
DM Camanchaca 2020_24_v2.xlsx
DM Camanchaca 2020_25.xlsx
DM Camanchaca 2020_26.xlsx
DM Camanchaca 2020_27.xlsx
DM Camanchaca 2020_28.xlsx
DM Camanchaca 2020_30.xlsx
DM Camanchaca 2020_31.xlsx
DM Camanchaca 2020_32.xlsx
DM Camanchaca 2020_33.xlsx
DM Camanchaca 2020_34.xlsx
DM Camanchaca_35 y 36.xlsx
DM Camanchaca_35 y 36 - Acceso directo.lnk
DM Camanchaca 2020_37.xlsx
DM Camanchaca 2020_38.xlsx
DM Camanchaca 2020_39.xlsx
DM Camanchaca 2020_40.xlsx
DM Camanchaca 2020_41.slk
Error en DM Camanchaca 2020_41.slk
DM Camanchaca 2020_41.slk.xls
DM Camanchaca 2020_42.xlsx
DM Camanchaca 2020_43.xlsx
DM Camanchaca 2020_45.xlsx
DM Camanchaca 2020_48.xlsx
DM Camanchaca 2020_50.xlsx
DM Camanchaca 2020_53.xlsx
DM Camanchaca 2020_06.xlsx
DM Camanchaca 2020_07.xlsx
DM Camanchaca 2020_8.xlsx
DM Camanchaca 2020_9.xlsx

In [669]:
camanchaca.dropna(axis=1, how='all',inplace=True)
camanchaca.dropna(axis=0, how='all',inplace=True)
camanchaca[0] = camanchaca[0].apply(lambda f: pd.to_datetime(f,errors='coerce'))

In [684]:
camanchaca1 = camanchaca[camanchaca[0].isnull()==False].copy()
camanchaca1.dropna(axis=1, how='all',inplace=True)
camanchaca1.dropna(axis=0, how='all',inplace=True)
camanchaca1 = camanchaca1[camanchaca1[0]>='01-01-2019']
camanchaca1 = camanchaca1.iloc[:,[0,1,2,3,4,5,6,7]]
camanchaca1.columns = ['FECHA','PRODUCTO','EMPAQUE','CALIBRE','CANTIDAD','PRECIO CFR','TIPO VENTA','PAIS']
camanchaca1.sample(20)

,FECHA,PRODUCTO,EMPAQUE,CALIBRE,CANTIDAD,PRECIO CFR,TIPO VENTA,PAIS
30,2019-02-28,JUGOSON,SIN SALSA,None,3750,2.40637,CONTRATO,RUSIA
22,2019-02-25,JUGOSON,CON SALSA CON ESTUCHE,None,157847,2.97736,CONTRATO,JAPON
34,2020-03-13,CARNE,GRANEL,C300-500,14000,2.81532,CONTRATO,RUSIA
23,2020-02-03,JUGOSON,SIN SALSA,None,17962.6,2.09439,CONTRATO,USA
20,2019-02-25,JUGOSON,CON SALSA CON ESTUCHE,None,4536,2.94043,CONTRATO,HONG KONG
11,2020-01-03,JUGOSON,SIN SALSA,None,19000,2.1,CONTRATO,COREA DEL SUR
3,2019-02-17,CARNE,GRANEL,C500-1000,20390,1.58563,CONTRATO,CHILE
85,2020-03-25,CARNE,GRANEL,C200-300,14000,3.05633,CONTRATO,RUSIA
30,2019-02-28,JUGOSON,SIN SALSA,None,3750,2.40637,CONTRATO,RUSIA
2,2020-01-27,JUGOSON,SIN SALSA,None,19800,1.95,CONTRATO,FRANCIA
39,2020-03-13,JUGOSON,CON SALSA CON ESTUCHE,None,7186.5,2.97345,CONTRATO,HONG KONG
1,2019-02-11,JUGOSON,SIN SALSA,None,19330,2.09,CONTRATO,ALEMANIA
28,2020-03-12,JUGOSON,CON SALSA CON ESTUCHE,None,15966.7,2.45776,CONTRATO,USA
1,2019-02-17,CARNE,GRANEL,C200-300,810,1.71248,CONTRATO,CHILE
4,2019-02-19,CARNE,GRANEL,C200-300,1200,1.69406,CONTRATO,CHILE
11,2020-03-05,JUGOSON,SIN SALSA,None,4000,1.75575,CONTRATO,MACEDONIA
72,2020-03-23,CARNE,GRANEL,C200-300,5000,2.96257,CONTRATO,USA
20,2019-02-25,JUGOSON,CON SALSA CON ESTUCHE,None,4536,2.94043,CONTRATO,HONG KONG
17,2020-03-09,CARNE,GRANEL,C500-1000,10000,1.50793,CONTRATO,CHILE
16,2020-02-01,JUGOSON,CON SALSA CON ESTUCHE,None,14288.4,3.2408,CONTRATO,USA

In [673]:
camanchaca2 = camanchaca[camanchaca[0].isnull()==False].copy()
camanchaca2.dropna(axis=1, how='all',inplace=True)
camanchaca2.dropna(axis=0, how='all',inplace=True)
camanchaca2 = camanchaca2[camanchaca2[0]<'01-01-2019']

In [676]:
camanchaca2 = camanchaca2.iloc[:,[1,2,3,4,5,6,7]]

In [678]:
camanchaca2.columns = ['FECHA','PRODUCTO','EMPAQUE','PAIS','CALIBRE','CANTIDAD','PRECIO CFR']

In [698]:
camanchaca3 = camanchaca[camanchaca[0].isnull()==True].copy()
camanchaca3.dropna(axis=1, how='all',inplace=True)
camanchaca3.dropna(axis=0, how='all',inplace=True)
camanchaca3[1] = camanchaca3[1].apply(lambda f: pd.to_datetime(f,errors='coerce'))
camanchaca3 = camanchaca3[camanchaca3[1].isnull()==False]
camanchaca3.dropna(axis=1, how='all',inplace=True)
camanchaca3.dropna(axis=0, how='all',inplace=True)
camanchaca3 = camanchaca3.loc[:,[1,2,3,4,5,6,7]]
camanchaca3.columns = ['FECHA','PRODUCTO','EMPAQUE','PAIS','CALIBRE','CANTIDAD','PRECIO CFR']
camanchaca3.head(20)

,FECHA,PRODUCTO,EMPAQUE,PAIS,CALIBRE,CANTIDAD,PRECIO CFR
4,2020-05-10,MEAT,GRANEL,Francia,200-300 U/KG,7.07,2.91061
5,2020-05-10,MEAT,GRANEL,Francia,300-500 U/KG,9.37,2.61964
6,2020-05-10,MEAT,GRANEL,Francia,500-UP U/KG,4.77,2.2065
7,2020-05-07,MEAT,GRANEL,Chile,0,5,1.43014
8,2020-05-07,MEAT,GRANEL,Federaci√≥n Rusa,200-300 U/KG,18,3.22
9,2020-05-07,MEAT,GRANEL,Federaci√≥n Rusa,300-500 U/KG,6,2.98
10,2020-05-07,MEAT,GRANEL,Italia,200-300 U/KG,24,3.25
11,2020-05-07,MEAT,GRANEL,Ucrania,100-200 U/KG,3,3.5
12,2020-05-07,MEAT,GRANEL,Ucrania,200-300 U/KG,20,3.2
13,2020-05-07,MEAT,GRANEL,Ucrania,300-500 U/KG,1,3
14,2020-05-07,WHO,FOODSERV,E.A.U.,20-35 U/LB,19.525,2.2
15,2020-05-07,WHO,FOODSERV,Federaci√≥n Rusa,60-80 U/KG,19.8,1.9
16,2020-05-07,WHO,FOODSERV,Federaci√≥n Rusa,40-60 U/KG,19.8,2.15
17,2020-05-06,MEAT,GRANEL,Chile,0,0.5,1.50089
18,2020-05-06,MEAT,GRANEL,Chile,200-300 U/KG,1,1.62096
19,2020-05-06,MEAT,GRANEL,Chile,300-500 U/KG,1,1.62096
20,2020-05-05,WHO,RETAIL,Japon,20-35 U/LB,15.7847,3.22
21,2020-05-05,WHO,FOODSERV,Singapur,20-35 U/LB,17.9626,2.15
22,2020-05-04,MEAT,GRANEL,Chile,300-500 U/KG,0.03,1.6708
23,2020-05-04,WHO,RETAIL,Estados Unidos,20-35 U/LB,31.6516,3.2408

In [699]:
camanchaca4 = camanchaca[camanchaca[0].isnull()==True].copy()
camanchaca4.dropna(axis=1, how='all',inplace=True)
camanchaca4.dropna(axis=0, how='all',inplace=True)
camanchaca4[1] = camanchaca4[1].apply(lambda f: pd.to_datetime(f,errors='coerce'))
camanchaca4 = camanchaca4[camanchaca4[1].isnull()]

In [710]:
camanchaca4.sample(20)
camanchaca4_a = camanchaca4.loc[:,[2,3,4,5,6,7,8,9,10,11,12,13]]
camanchaca4_a = camanchaca4_a.loc[:,[2,3,4,5,6,7,8]]
camanchaca4_a.columns = ['FECHA','PRODUCTO','EMPAQUE','PAIS','CALIBRE','CANTIDAD','PRECIO CFR']
camanchaca4_a.dropna(thresh = 3, axis=0, inplace=True)
camanchaca4_a.drop(camanchaca4_a[camanchaca4_a.FECHA == 'Fecha Factura'].index, axis=0,inplace=True)
camanchaca4_a.drop(camanchaca4_a[camanchaca4_a.FECHA == 'Forma'].index, axis=0,inplace=True)
camanchaca4_a.drop(camanchaca4_a[camanchaca4_a.FECHA == 'Total general'].index, axis=0,inplace=True)
camanchaca4_a.sample(20)

,FECHA,PRODUCTO,EMPAQUE,PAIS,CALIBRE,CANTIDAD,PRECIO CFR
350,2020-04-16 00:00:00,MEAT,GRANEL,Federaci√≥n Rusa,200-300 U/KG,24,3.04009
475,2020-01-29 00:00:00,WHO,FOODSERV,Alemania,20-35 U/LB,19.59,1.79592
464,2020-02-05 00:00:00,MEAT,GRANEL,Alemania,300-500 U/KG,24,2.82558
152,2020-08-04 00:00:00,MEAT,GRANEL,Federaci√≥n Rusa,300-500 U/KG,29,2.79458
233,2020-06-19 00:00:00,MEAT,GRANEL,Japon,100-200 U/KG,12,5.70817
118,2020-08-18 00:00:00,MEAT,RETAIL,Francia,300-500 U/KG,21.6,2.91788
461,2020-02-06 00:00:00,MEAT,GRANEL,Ucrania,300-500 U/KG,24,2.73687
114,2020-02-27 00:00:00,MEAT,GRANEL,Chile,200-300 U/KG,5.14,1.66441
117,2020-08-23 00:00:00,WHO,FOODSERV,M√©xico,20-35 U/LB,11.6,1.58052
428,2020-02-28 00:00:00,WHO,FOODSERV,Lituania,40-60 U/KG,19.795,1.7916
182,2020-07-15 00:00:00,MEAT,GRANEL,Ucrania,200-300 U/KG,24,3.06472
210,2020-01-02 00:00:00,MEAT,GRANEL,Ucrania,200-300 U/KG,24,2.9855
82,2020-09-08 00:00:00,MEAT,GRANEL,Dinamarca,500-UP U/KG,24,2.48136
106,2020-08-27 00:00:00,MEAT,RETAIL,Australia,100-200 U/KG,4,3.27024
276,2020-05-30 00:00:00,WHO,RETAIL,Estados Unidos,20-35 U/LB,0,0
144,2020-08-10 00:00:00,WHO,FOODSERV,Estados Unidos,20-35 U/LB,31.5706,1.74227
55,2020-09-24 00:00:00,MEAT,GRANEL,Federaci√≥n Rusa,300-500 U/KG,71.03,2.77212
61,2020-03-19 00:00:00,MEAT,GRANEL,Chile,300-500 U/KG,0.65,0.753457
439,2020-02-21 00:00:00,MEAT,GRANEL,Estados Unidos,200-300 U/KG,9.6,2.99177
202,2020-01-16 00:00:00,WHO,FOODSERV,Estados Unidos,20-35 U/LB,17.9626,1.90033

In [722]:
camanchaca4_b = camanchaca.loc[:,['Unnamed: 1', 'Unnamed: 10', 'Unnamed: 11',
        'Unnamed: 2',  'Unnamed: 3',  'Unnamed: 4',  'Unnamed: 5',
        'Unnamed: 6',  'Unnamed: 7',  'Unnamed: 9']]
camanchaca4_b.dropna(axis=1, how='all',inplace=True)
camanchaca4_b.dropna(axis=0, how='all',inplace=True)
camanchaca4_b = camanchaca4_b.loc[:,['Unnamed: 1','Unnamed: 2','Unnamed: 3','Unnamed: 4','Unnamed: 5','Unnamed: 6','Unnamed: 7']]
camanchaca4_b.columns = ['FECHA','PRODUCTO','EMPAQUE','PAIS','CALIBRE','CANTIDAD','PRECIO CFR']
camanchaca4_b.drop(camanchaca4_b[camanchaca4_b.FECHA == 'Fecha Factura'].index, axis=0,inplace=True)
camanchaca4_b.drop(camanchaca4_b[camanchaca4_b.FECHA == 'Forma'].index, axis=0,inplace=True)
camanchaca4_b.drop(camanchaca4_b[camanchaca4_b.FECHA == 'Total general'].index, axis=0,inplace=True)
camanchaca4_b.dropna(inplace=True)
camanchaca4_b.sample(20)

,FECHA,PRODUCTO,EMPAQUE,PAIS,CALIBRE,CANTIDAD,PRECIO CFR
245,2020-05-25 00:00:00,WHO,FOODSERV,Japon,50-70 U/KG,15.95,2.16088
176,2020-06-23 00:00:00,WHO,RETAIL,Estados Unidos,20-35 U/LB,63.585,2.96357
96,2020-08-11 00:00:00,WHO,FOODSERV,Japon,50-70 U/KG,15.95,2.14414
232,2020-06-01 00:00:00,WHO,FOODSERV,Japon,50-70 U/KG,15.95,2.10727
142,2020-07-14 00:00:00,WHO,RETAIL,Hong Kong,20-35 U/LB,3.15,3.2
66,2020-08-27 00:00:00,MEAT,GRANEL,Francia,500-UP U/KG,12.13,2.49583
275,2020-05-07 00:00:00,MEAT,GRANEL,Italia,200-300 U/KG,24,3.10592
63,2020-08-27 00:00:00,MEAT,RETAIL,Australia,100-200 U/KG,4,3.27024
141,2020-07-15 00:00:00,WHO,FOODSERV,Estados Unidos,20-35 U/LB,0,0
25,2020-09-13 00:00:00,MEAT,GRANEL,Federaci√≥n Rusa,200-300 U/KG,14,2.96395
400,2020-02-17 00:00:00,MEAT,RETAIL,Japon,100-200 U/KG,10.8,3.57583
441,2020-01-21 00:00:00,WHO,FOODSERV,Japon,50-70 U/KG,31.89,2.13051
44,2020-09-08 00:00:00,WHO,FOODSERV,Federaci√≥n Rusa,40-60 U/KG,5,1.9124
443,2020-01-20 00:00:00,MEAT,RETAIL,Estados Unidos,200-300 U/KG,6.73151,6.28509
247,2020-05-22 00:00:00,MEAT,GRANEL,Federaci√≥n Rusa,200-300 U/KG,5,3.02461
260,2020-05-15 00:00:00,MEAT,RETAIL,Francia,300-500 U/KG,21.6,3.25995
264,2020-05-15 00:00:00,MEAT,GRANEL,Ruman√≠a,300-500 U/KG,9.01,2.80267
423,2020-02-04 00:00:00,WHO,RETAIL,Japon,20-35 U/LB,15.7847,3.04895
73,2020-08-23 00:00:00,WHO,RETAIL,Estados Unidos,20-35 U/LB,15.7847,2.15864
447,2020-01-16 00:00:00,MEAT,GRANEL,Ucrania,200-300 U/KG,24,2.9855

In [723]:
camanchaca = pd.concat([camanchaca1,camanchaca2,camanchaca3,camanchaca4_a,camanchaca4_b], ignore_index=True)

In [724]:
camanchaca.head()

,FECHA,PRODUCTO,EMPAQUE,CALIBRE,CANTIDAD,PRECIO CFR,TIPO VENTA,PAIS
0,2020-03-02 00:00:00,CARNE,GRANEL,C300-500,24000,2.78737,CONTRATO,RUSIA
1,2020-03-02 00:00:00,JUGOSON,SIN SALSA,None,1500,1.82964,CONTRATO,MEXICO
2,2020-03-02 00:00:00,JUGOSON,SIN SALSA,None,4000,1.76154,CONTRATO,MEXICO
3,2020-03-02 00:00:00,JUGOSON,SIN SALSA,None,19200,1.65428,CONTRATO,MEXICO
4,2020-03-02 00:00:00,JUGOSON,SIN SALSA,None,18276.7,1.83971,CONTRATO,USA

In [725]:
# Transformaciones
camanchaca.FECHA = camanchaca.FECHA.apply(lambda f: pd.to_datetime(f,errors='coerce'))
camanchaca.CANTIDAD = camanchaca.CANTIDAD.apply(lambda c: pd.to_numeric(c,errors='coerce'))
camanchaca['PRECIO CFR'] = camanchaca['PRECIO CFR'].apply(lambda p: pd.to_numeric(p,errors='coerce'))
camanchaca.CALIBRE = camanchaca.CALIBRE.apply(lambda x: x if pd.isnull(str(x)) else str(x).split(" ")[0])
camanchaca.PAIS = camanchaca.PAIS.apply(str.capitalize)
camanchaca.reset_index(drop = True, inplace=True)

In [726]:
# Eliminar duplicados
camanchaca.drop_duplicates(inplace=True)
# Creaci√≥n de campos
camanchaca['EMPRESA'] = 'Camanchaca'
camanchaca['SEMANA'] = camanchaca.FECHA.apply(lambda d: d.isocalendar()[1])

In [727]:
# Chequeo
camanchaca.info()
camanchaca.sample(20)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1483 entries, 0 to 11272
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   FECHA       1483 non-null   datetime64[ns]
 1   PRODUCTO    1483 non-null   object
 2   EMPAQUE     1483 non-null   object
 3   CALIBRE     1483 non-null   object
 4   CANTIDAD    1483 non-null   float64
 5   PRECIO CFR  1483 non-null   float64
 6   TIPO VENTA  181 non-null    object
 7   PAIS        1483 non-null   object
 8   EMPRESA     1483 non-null   object
 9   SEMANA      1483 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(1), object(6)
memory usage: 127.4+ KB

,FECHA,PRODUCTO,EMPAQUE,CALIBRE,CANTIDAD,PRECIO CFR,TIPO VENTA,PAIS,EMPRESA,SEMANA
472,2020-01-22,MEAT,RETAIL,200-300,21.600000,3.407563,NaN,Francia,Camanchaca,4
10844,2020-09-13,WHO,FOODSERV,20-35,0.866376,1.735553,NaN,Estados unidos,Camanchaca,37
2801,2020-06-09,MEAT,GRANEL,200-300,0.100000,1.000000,NaN,Chile,Camanchaca,24
179,2019-02-28,JUGOSON,SIN SALSA,None,3750.000000,2.406370,CONTRATO,Rusia,Camanchaca,9
382,2020-03-05,MEAT,GRANEL,300-500,24.000000,2.739583,NaN,Federaci√≥n rusa,Camanchaca,10
11229,2020-02-10,WHO,FOODSERV,50-70,15.950000,2.106270,NaN,Japon,Camanchaca,7
11238,2020-02-04,WHO,FOODSERV,20-35,36.814469,1.834142,NaN,Estados unidos,Camanchaca,6
15,2020-03-09,CARNE,GRANEL,C500-1000,20000.000000,1.507932,CONTRATO,Chile,Camanchaca,11
421,2020-02-19,WHO,FOODSERV,50-70,1.100000,1.879784,NaN,Chile,Camanchaca,8
9107,2020-11-01,WHO,RETAIL,20-35,5.850000,2.973880,NaN,Hong kong,Camanchaca,44
7273,2020-08-23,WHO,FOODSERV,20-35,11.600000,1.673879,NaN,M√©xico,Camanchaca,34
741,2020-05-10,MEAT,GRANEL,300-500,24.000000,3.000000,NaN,Alemania,Camanchaca,19
11178,2020-03-12,WHO,RETAIL,20-35,30.255120,2.541455,NaN,Estados unidos,Camanchaca,11
418,2020-02-20,MEAT,GRANEL,300-500,9.860000,1.693002,NaN,Chile,Camanchaca,8
11023,2020-06-10,MEAT,GRANEL,300-500,24.000000,2.761583,NaN,Federaci√≥n rusa,Camanchaca,24
11141,2020-03-30,MEAT,RETAIL,100-200,10.800000,3.775370,NaN,Japon,Camanchaca,14
11219,2020-02-14,WHO,FOODSERV,60-80,19.800000,1.668333,NaN,Francia,Camanchaca,7
2439,2020-06-15,WHO,RETAIL,20-35,15.784700,2.953032,NaN,Japon,Camanchaca,25
5139,2020-08-10,WHO,FOODSERV,40-60,11.275000,1.845052,NaN,Federaci√≥n rusa,Camanchaca,33
5499,2020-08-23,WHO,RETAIL,20-35,15.784700,2.158643,NaN,Estados unidos,Camanchaca,34

In [728]:
camanchaca.PRODUCTO.unique()

array(['CARNE', 'JUGOSON', 'MEAT', 'WHO'], dtype=object)

### St. Andrews

In [241]:
#Lectura de datos
standrews = pd.DataFrame()

for w in weeks:
    try:
        os.chdir(prices+str(year)+'/'+str(w))
    except:
        print('Error al ingresar a', w)
        continue
    w_files = os.listdir(prices+str(year)+'/'+str(w)+'/')
    for file in w_files:
        if 'st andrews' in file.lower():
            print(file)
            if file[-4:] != '.lnk':
                # Casos XLS
                if file[-4:] in ['.xls','.slk'] :
                    try:
                        df = pd.read_excel(prices+str(year)+'/'+str(w)+'/'+file, skiprows=1)
                        #Anexar
                        df['ARCHIVO'] = file
                        standrews = standrews.append(df)
                        
                    except:
                        print('Error en', file)
                else: # Casos XLSX
                    try: 
                        #Leer hoja donde est√° la tabla
                        wb = load_workbook(filename = prices+str(year)+'/'+str(w)+'/'+file, skiprows=1)
                        hoja = wb.sheetnames
                        sheet = wb[hoja[0]]

                        #Transformar hoja en un df
                        df = pd.DataFrame(sheet.values) 
                        df.dropna(axis=0, thresh=2, inplace=True)
                        df['ARCHIVO'] = file

                        #Anexar
                        standrews = standrews.append(df)
                    except:
                        print('Error en', file)

DM St Andrews 2020_10.xls
DM St Andrews 2020_11.xls
DM St Andrews 2020_12.xls
DM St Andrews 2020_13.xls
DM St Andrews 2020_14.xls
DM St Andrews 2020_15.xls
DM St Andrews 2020_16.xls
DM St Andrews 2020_17.xls
DM St Andrews 2020_18.xls
DM St Andrews 2020_19.xls
DataSalmon 2 St Andrews.xls
DM St Andrews 2020_20.xls
DM St Andrews 2020_21.xls
DM St Andrews 2020_22.xls
DM St Andrews 2020_23.xls
DM St Andrews 2020_24.xls
DM St Andrews 2020_25.xls
DM St Andrews 2020_26.xls
DM St Andrews 2020_27.xls
DM St Andrews 2020_28.xls
DM St Andrews 2020_29.xls
DM 3 St ANdrews.xls
DM St Andrews 2020_30.xls
DM St Andrews 2020_31.xls
DM St Andrews 2020_32.xls
DM St Andrews 2020_33.xls
DM St Andrews 2020_34.xls
DM St Andrews 2020_35.xls
DM St Andrews 2020_36.xls
DM St Andrews 2020_37.xls
DM St Andrews 2020_38.xls
DM St Andrews 2020_39.xls
DataMussel 4 St Andrews.xls
DM St Andrews 2020_40.xls
DM St Andrews 2020_41.xls
DM St Andrews 2020_42.xls
DM St Andrews 2020_43.xls
DM St Andrews 2020_44.xls
DM St Andrews 2020_45.xls
DM St Andrews 2020_46.xls
DM St Andrews 2020_47.xls
DM St Andrews 2020_48.xls
DM St Andrews 2020_49.xls
DM St Andrews 2020_50.xls
DM St Andrews 2020_51.xls
DM St Andrews 2020_52.xls
DM St Andrews 2020_53.xls
DM St Andrews 6 2020.xls
DM St Andrews 2020_07.xls
DM St Andrews 2020_08.xls
DM St Andrews 2020_09.xls

In [242]:
# Completar valores
standrews['EMPAQUE'].fillna(standrews['Empaque'], inplace=True)
standrews['VENTA'].fillna(standrews['Venta'], inplace=True)
standrews['Precio CFR'].fillna(standrews['Precio Unitario'], inplace = True)
standrews['Precio CFR'].fillna(standrews['Precio Unitario CFR/kilo'], inplace = True)
standrews['FOB por Kilo'].fillna(standrews['FOB x Kilo'], inplace = True)
standrews['FOB por Kilo'].fillna(standrews['Unnamed: 8'], inplace = True)
standrews['VENTA'].fillna(standrews['VENTA '], inplace = True)
standrews['VENTA'].fillna(standrews['VENTAS'], inplace = True)
standrews['Pais'].fillna(standrews['Mercado'], inplace = True)

In [243]:
standrews.drop(['Empaque','Venta','Precio Unitario','Precio Unitario CFR/kilo','Mercado', 'FOB x Kilo','Venta FOB','Unnamed: 8','VENTAS','VENTA ','Precio CFR'], axis=1, inplace=True)
standrews

,Fecha Carga Estimada,Producto Global,EMPAQUE,Calibre,Peso,FOB por Kilo,VENTA,Pais,ARCHIVO
0,2020-03-03 00:00:00,CARNE,RETAIL COMPENSADO,C200-500,20000.00,3.54,PROGRAMA,FRANCE,DM St Andrews 2020_10.xls
1,2020-03-04 00:00:00,CARNE,GRANEL,C300-500,19990.00,2.54,PROGRAMA,ENGLAND,DM St Andrews 2020_10.xls
2,2020-03-02 00:00:00,ENTERO,SIN SALSA,18-27 U/LB,17079.48,2.01,PROGRAMA,USA,DM St Andrews 2020_10.xls
3,2020-03-02 00:00:00,ENTERO,SIN SALSA,E-40-60,20000.00,1.79,PROGRAMA,RUSSIA,DM St Andrews 2020_10.xls
4,2020-03-03 00:00:00,CARNE,RETAIL NO COMPENSADO,C100-200,22000.00,3.37,PROGRAMA,THAILAND,DM St Andrews 2020_10.xls
...,...,...,...,...,...,...,...,...,...
44,2020-02-28 00:00:00,ENTERO,CON SALSA,E-23-32,13605.00,2.74,PROGRAMA,USA,DM St Andrews 2020_09.xls
45,2020-02-25 00:00:00,CARNE,GRANEL,C200-300,23000.00,2.90,PROGRAMA,COREA,DM St Andrews 2020_09.xls
46,2020-02-24 00:00:00,CARNE,GRANEL,C300-500,23000.00,2.74,PROGRAMA,RUSIA,DM St Andrews 2020_09.xls
47,2020-02-25 00:00:00,CARNE,GRANEL,C300-500,23000.00,2.74,PROGRAMA,RUSIA,DM St Andrews 2020_09.xls
48,NaT,NaN,NaN,NaN,483310.08,NaN,NaN,NaN,DM St Andrews 2020_09.xls

In [244]:
standrews.columns

Index(['Fecha Carga Estimada', 'Producto Global', 'EMPAQUE', 'Calibre', 'Peso',
       'FOB por Kilo', 'VENTA', 'Pais', 'ARCHIVO'],
      dtype='object')

In [245]:
standrews.dropna(axis=0, thresh=5, inplace=True)

In [246]:
standrews.columns = ['FECHA','PRODUCTO','EMPAQUE','CALIBRE','CANTIDAD','PRECIO CFR','TIPO VENTA', 'PAIS','ARCHIVO']
standrews[standrews.FECHA.isnull()]

Empty DataFrame
Columns: [FECHA, PRODUCTO, EMPAQUE, CALIBRE, CANTIDAD, PRECIO CFR, TIPO VENTA, PAIS, ARCHIVO]
Index: []

In [247]:
# Modificaciones columnas 

standrews['EMPRESA'] = 'St Andrews'
standrews['FECHA'] = standrews.FECHA.apply(lambda f: pd.to_datetime(f, errors='coerce'))
standrews['SEMANA'] = standrews.FECHA.apply(lambda f: f.isocalendar()[1])
standrews.CALIBRE = standrews.CALIBRE.apply(lambda x: str(x).split(" ")[0])
standrews['PRECIO CFR'] = standrews['PRECIO CFR'].apply(lambda p: pd.to_numeric(p, errors='coerce'))
standrews.sort_values(by='FECHA', ascending = True, inplace = True)

In [248]:
#standrews.drop_duplicates(subset=['FECHA','PRODUCTO','EMPAQUE','CALIBRE','PAIS'],inplace= True)
standrews.drop_duplicates(inplace=True)

In [249]:
standrews.reset_index(inplace= True, drop=True)

In [250]:
standrews.CALIBRE.unique()

array(['C200-300', '40-60', 'E-23-32', 'E-23-29', 'C90-150', 'C300-500',
       'E20-30', 'C100-200', 'E-50-80', '18-27', 'E-50-70', 'MC40-60',
       'MC60-80', 'E-60-80', 'E-40-60', '35-45', 'MC100-120', 'C200-500',
       'E60-80', 'MC80-100', 'SIN', 'E50-70', 'MC20-40', '27-36',
       'C40-100', 'C500-800', 'nan', 'C'], dtype=object)

In [127]:
standrews.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1382 entries, 4 to 1425
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   FECHA       1382 non-null   datetime64[ns]
 1   PRODUCTO    1382 non-null   object
 2   EMPAQUE     1382 non-null   object
 3   CALIBRE     1382 non-null   object
 4   CANTIDAD    1382 non-null   float64
 5   PRECIO CFR  1219 non-null   float64
 6   TIPO VENTA  1382 non-null   object
 7   PAIS        1382 non-null   object
 8   EMPRESA     1382 non-null   object
 9   SEMANA      1382 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(1), object(6)
memory usage: 118.8+ KB

In [253]:
standrews.drop(['ARCHIVO'], axis=1, inplace=True)

In [255]:
standrews.sample(10)

,FECHA,PRODUCTO,EMPAQUE,CALIBRE,CANTIDAD,PRECIO CFR,TIPO VENTA,PAIS,EMPRESA,SEMANA
870,2020-08-04,CARNE,GRANEL,C200-300,23000.0,2.940000,PROGRAMA,BELGIUM,St Andrews,32
1053,2020-09-07,CARNE,GRANEL,C200-300,23000.0,2.873913,PROGRAMA,RUSSIA,St Andrews,37
401,2020-04-16,ENTERO,SIN SALSA,E-40-60,5000.0,2.170000,PROGRAMA,CHINA,St Andrews,16
183,2020-02-26,CARNE,RETAIL COMPENSADO,C200-300,9780.0,3.240000,PROGRAMA,FRANCIA,St Andrews,9
5,2020-01-07,CARNE,RETAIL COMPENSADO,C90-150,2270.0,3.380000,PROGRAMA,USA,St Andrews,2
281,2020-03-11,CARNE,GRANEL,C100-200,9200.0,3.150000,PROGRAMA,UCRANIA,St Andrews,11
498,2020-05-12,CARNE,GRANEL,C300-500,6300.0,3.070000,PROGRAMA,ITALY,St Andrews,20
185,2020-02-26,CARNE,RETIAL NO COMPENSADO,C100-200,999.0,3.640000,PROGRAMA,UCRANIA,St Andrews,9
526,2020-05-18,CARNE,RETAIL NO COMPENSADO,C100-200,22000.0,3.370000,PROGRAMA,THAILAND,St Andrews,21
579,2020-05-25,CARNE,GRANEL,C200-300,16410.0,2.950000,PROGRAMA,FRANCE,St Andrews,22

In [418]:
standrews.PRODUCTO.unique()

array(['CARNE', 'ENTERO', 'MEDIA CONCHA', 'ENTERO IQF'], dtype=object)

### Sudmaris

In [267]:
#Lectura de datos
sudmaris = pd.DataFrame()

for w in weeks:
    try:
        os.chdir(prices+str(year)+'/'+str(w))
    except:
        print('Error al ingresar a', w)
        continue
    w_files = os.listdir(prices+str(year)+'/'+str(w)+'/')
    for file in w_files:
        if 'sudmaris' in file.lower():
            print(file)
            if file[-4:] != '.lnk':
                # Casos XLS
                if file[-4:] in ['.xls','.slk'] :
                    try:
                        df = pd.read_excel(prices+str(year)+'/'+str(w)+'/'+file, skiprows=1)
                        
                        #Anexar
                        df['ARCHIVO'] = file
                        sudmaris = sudmaris.append(df)
                        
                    except:
                        print('Error en', file)
                else: # Casos XLSX
                    try: 
                        #Leer hoja donde est√° la tabla
                        wb = load_workbook(filename = prices+str(year)+'/'+str(w)+'/'+file)
                        hoja = wb.sheetnames
                        sheet = wb['Hoja1']

                        #Transformar hoja en un df
                        df = pd.DataFrame(sheet.values) 

                        #Anexar
                        df['ARCHIVO'] = file
                        sudmaris = sudmaris.append(df)
                    except:
                        print('Error en', file)

DM Sudmaris 2020_10.xlsx
DM Sudmaris 2020_11.xlsx
DM Sudmaris 2020_14.xlsx
DM Sudmaris 2020_16.xlsx
DM Sudmaris 2020_17.xlsx
DM Sudmaris 2020_18.xlsx
DM Sudmaris 2020_19.xlsx
DataMussel 2 Sudmaris.xlsx
DM Sudmaris 2020_20.xlsx
DM Sudmaris 2020_21.xlsx
DM Sudmaris 2020_22.xlsx
DM Sudmaris 2020_23.xlsx
DM Sudmaris 2020_24.xlsx
DM Sudmaris 2020_25.xlsx
DM Sudmaris 2020_26.xlsx
DM Sudmaris 2020_27.xlsx
DM Sudmaris 2020_28.xlsx
DM Sudmaris 2020_29.xlsx
DataMussel 3 Sudmaris.xlsx
DM Sudmaris 2020_30.xlsx
DM Sudmaris 2020_31.xlsx
DM Sudmaris 2020_32.xlsx
DM Sudmaris 2020_33.xlsx
DM Sudmaris 2020_34.xlsx
DM Sudmaris 2020_35.xlsx
DM Sudmaris 2020_36.xlsx
DM Sudmaris 2020_37.xlsx
DM Sudmaris 2020_38.xlsx
DM Sudmaris 2020_39.xlsx
DataMussel 4 Sudmaris.xlsx
DM Sudmaris 2020_40.xlsx
DM Sudmaris 2020_41.xlsx
DM Sudmaris 2020_43.xlsx
DM Sudmaris 2020_44.xlsx
DM Sudmaris 2020_45.xlsx
DM Sudmaris 2020_46.xlsx
DM Sudmaris 2020_47.xlsx
DM Sudmaris 2020_48.xlsx
DM Sudmaris 5.xlsx
DM Sudmaris 2020_51.xlsx
DM Sudmaris 2020_53.xls.xlsx
DM Sudmaris 6.xlsx
Sudmaris 2020_07.xlsx
DM Sudmaris 2020_8.xlsx
DM Sudmaris 2020_9.xlsx

In [268]:
sudmaris.head(10)

,0,1,2,3,4,5,6,7,8,9,10,ARCHIVO,11
0,FECHA,PRODUCTO,Empaque,CALIBRE,CANTIDAD,PRECIO CFR,PRECIO FOB,TIPO VENTA,DESTINO,None,None,DM Sudmaris 2020_10.xlsx,NaN
1,2020-03-02 00:00:00,Carne,Granel,C100-200,10180,3.3,=F2-0.18,Contrato,Espa√±a,None,None,DM Sudmaris 2020_10.xlsx,NaN
2,2020-03-02 00:00:00,Carne,Granel,C200-300,13820,3,=F3-0.18,Contrato,Espa√±a,None,None,DM Sudmaris 2020_10.xlsx,NaN
3,2020-03-02 00:00:00,Media Concha,Retail,C60-80,9036.1,4.68,=F4-0.18,Contrato,USA,None,None,DM Sudmaris 2020_10.xlsx,NaN
4,2020-03-02 00:00:00,Entero,Sin Salsa,C60-80,4487.79,2,=F5-0.18,Contrato,USA,None,None,DM Sudmaris 2020_10.xlsx,NaN
5,2020-03-02 00:00:00,Entero,Sin Salsa,C40-60,4190.89,2.15,=F6-0.18,Contrato,USA,None,None,DM Sudmaris 2020_10.xlsx,NaN
6,2020-03-02 00:00:00,Carne,Retail,C300-500,4000,2.58,=F7-0.18,Spot,Chile,None,None,DM Sudmaris 2020_10.xlsx,NaN
7,2020-03-03 00:00:00,Entero,Sin Salsa,C40-60,17978.4,2.15,=F8-0.18,Contrato,USA,None,None,DM Sudmaris 2020_10.xlsx,NaN
8,2020-03-03 00:00:00,Carne,Granel,C300-500,24000,3.03,=F9-0.18,Spot,Brasil,None,None,DM Sudmaris 2020_10.xlsx,NaN
9,2020-03-04 00:00:00,Entero,Sin Salsa,C60-80,18700,1.85,=F10-0.18,Spot,Italia,None,None,DM Sudmaris 2020_10.xlsx,NaN

In [269]:
# Eliminar fila semanas y Nan
sudmaris.drop(sudmaris.iloc[:,[0,10,12]], axis=1, inplace=True)

#Corregir nombres de columnas
sudmaris.columns = sudmaris.iloc[0,:]
sudmaris.reset_index(inplace=True, drop=True)
sudmaris.drop(sudmaris.iloc[0].index.name,inplace= True)

In [270]:
sudmaris.sample(10)

,PRODUCTO,Empaque,CALIBRE,CANTIDAD,PRECIO CFR,PRECIO FOB,TIPO VENTA,DESTINO,NaN,DM Sudmaris 2020_10.xlsx
3805,2020-04-22 00:00:00,Carne,Granel,C200-300,7340,2.95,=G93-0.18,Contrato,Italia,DM Sudmaris 2020_38.xlsx
4192,2020-06-03 00:00:00,Carne,Granel,C300-500,24000,3.15,=G161-0.18,Contrato,Rusia,DM Sudmaris 2020_39.xlsx
1556,2020-05-12 00:00:00,Media Concha,Retail,C80-100,9000,4.55,=G120-0.18,Contrato,Italia,DM Sudmaris 2020_30.xlsx
2396,2020-06-04 00:00:00,Carne,Granel,C300-500,20260,3,=G164-0.18,Spot,Belgica,DM Sudmaris 2020_33.xlsx
4946,2020-07-10 00:00:00,Carne,Granel,C200-300,4820,3.12,=G234-0.18,Contrato,Francia,DM Sudmaris 2020_41.xlsx
5690,2020-07-23 00:00:00,Entero,Sin Salsa,C60-80,6000,2.05,=G252-0.18,Contrato,Italia,DM Sudmaris 2020_44.xlsx
6056,2020-07-15 00:00:00,Carne,Granel,C200-300,12000,3.2,=G239-0.18,Contrato,Rusia,DM Sudmaris 2020_45.xlsx
2367,2020-05-25 00:00:00,Carne,Granel,C300-500,6470,3,=G135-0.18,Contrato,Rusia,DM Sudmaris 2020_33.xlsx
1379,2020-06-17 00:00:00,Carne,Granel,C300-500,24000,3.05,=G192-0.18,Contrato,Rusia,DM Sudmaris 2020_29.xlsx
1226,2020-03-04 00:00:00,Entero,Sin Salsa,C40-60,19210,2.6,=G39-0.18,Spot,UAE,DM Sudmaris 2020_29.xlsx

In [271]:
# Modificaciones columnas 
sudmaris.columns = ['FECHA','PRODUCTO','EMPAQUE','CALIBRE','CANTIDAD','PRECIO CFR', 'PRECIO FOB','TIPO VENTA', 'PAIS','ARCHIVO']
sudmaris['EMPRESA'] = 'Sudmaris'
sudmaris.FECHA = sudmaris.FECHA.apply(lambda f: pd.to_datetime(f, errors='coerce'))
sudmaris.drop(sudmaris.loc[sudmaris.FECHA.isna()].index, axis=0, inplace = True)

In [272]:
# Transformaciones en columnas
sudmaris['SEMANA'] = sudmaris.FECHA.apply(lambda f: f.isocalendar()[1])
sudmaris.CALIBRE = sudmaris.CALIBRE.apply(lambda x: str(x).split(" ")[0])
sudmaris.CANTIDAD = sudmaris.CANTIDAD.apply(lambda c: pd.to_numeric(c, errors='coerce'))
sudmaris['PRECIO CFR'] = sudmaris['PRECIO CFR'].apply(lambda c: pd.to_numeric(c, errors='coerce'))
sudmaris['PRECIO FOB'] = sudmaris['PRECIO FOB'].apply(lambda c: pd.to_numeric(c, errors='coerce'))
sudmaris.sort_values(by='FECHA', ascending = True, inplace = True)
sudmaris.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8011 entries, 139 to 8232
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   FECHA       8011 non-null   datetime64[ns]
 1   PRODUCTO    8011 non-null   object
 2   EMPAQUE     8011 non-null   object
 3   CALIBRE     8011 non-null   object
 4   CANTIDAD    8011 non-null   float64
 5   PRECIO CFR  7979 non-null   float64
 6   PRECIO FOB  0 non-null      float64
 7   TIPO VENTA  7979 non-null   object
 8   PAIS        8011 non-null   object
 9   ARCHIVO     8011 non-null   object
 10  EMPRESA     8011 non-null   object
 11  SEMANA      8011 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(1), object(7)
memory usage: 813.6+ KB

In [274]:
sudmaris.drop_duplicates(inplace= True)

In [275]:
sudmaris = sudmaris[['FECHA','PRODUCTO','EMPAQUE','CALIBRE','CANTIDAD','PRECIO CFR','PAIS','EMPRESA','SEMANA']]

In [276]:
sudmaris.head()

,FECHA,PRODUCTO,EMPAQUE,CALIBRE,CANTIDAD,PRECIO CFR,PAIS,EMPRESA,SEMANA
139,2020-02-11,Media Concha,Granel,C60-80,21890.0,4.09,Usa,Sudmaris,7
6202,2020-02-11,Carne,Granel,C300-500,24000.0,2.85,Francia,Sudmaris,7
1692,2020-02-11,Carne,Granel,C300-500,24000.0,2.85,Francia,Sudmaris,7
1691,2020-02-11,Media Concha,Granel,C60-80,21890.0,4.09,Usa,Sudmaris,7
6584,2020-02-11,Media Concha,Granel,C60-80,21890.0,4.09,Usa,Sudmaris,7

In [277]:
sudmaris.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7749 entries, 139 to 8232
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   FECHA       7749 non-null   datetime64[ns]
 1   PRODUCTO    7749 non-null   object
 2   EMPAQUE     7749 non-null   object
 3   CALIBRE     7749 non-null   object
 4   CANTIDAD    7749 non-null   float64
 5   PRECIO CFR  7717 non-null   float64
 6   PAIS        7749 non-null   object
 7   EMPRESA     7749 non-null   object
 8   SEMANA      7749 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 605.4+ KB

In [278]:
sudmaris.drop_duplicates(inplace=True)

In [281]:
sudmaris.sample(20)

,FECHA,PRODUCTO,EMPAQUE,CALIBRE,CANTIDAD,PRECIO CFR,PAIS,EMPRESA,SEMANA
7603,2020-07-01,Media Concha,Granel,C100-120,5019.00,3.33,Espa√±a,Sudmaris,27
2846,2020-03-06,Entero,Sin Salsa,C60-80,17978.40,2.00,USA,Sudmaris,10
6927,2020-10-07,Entero,Sin salsa,60-80,19220.00,1.80,Rusia,Sudmaris,41
827,2020-04-27,Carne,Granel,C200-300,10000.00,3.20,Italia,Sudmaris,18
5115,2020-03-09,Media Concha,Granel,C60-80,4994.00,4.00,Mexico,Sudmaris,11
1029,2020-04-07,Entero,Sin Salsa,C60-80,17978.40,1.82,USA,Sudmaris,15
4501,2020-05-22,Carne,Granel,C100-200,5000.00,3.62,Belgica,Sudmaris,21
4172,2020-05-27,Media Concha,Granel,C60-80,18007.00,4.15,Espa√±a,Sudmaris,22
6993,2020-02-26,Entero,Sin Salsa,C60-80,17978.40,2.03,USA,Sudmaris,9
5033,2020-09-23,Entero,Sin Salsa,,18531.18,1.90,USA,Sudmaris,39
5798,2020-10-16,Carne,Sin salsa,300-500,5920.00,3.55,Francia,Sudmaris,42
6449,2020-07-22,Entero,Sin Salsa,C40-60,19220.00,2.15,Rusia,Sudmaris,30
7854,2020-03-12,Carne,Retail,C200-300,9034.60,4.16,USA,Sudmaris,11
1923,2020-07-10,Carne,Granel,C200-300,4820.00,3.12,Francia,Sudmaris,28
7988,2020-06-19,Carne,Granel,C200-300,2000.00,3.23,Francia,Sudmaris,25
7033,2020-03-19,Carne,Granel,C200-300,10000.00,3.20,Italia,Sudmaris,12
3673,2020-08-11,Media Concha,Granel,C60-80,22000.00,4.05,USA,Sudmaris,33
467,2020-05-29,Carne,Retail,C200-300,3314.20,4.13,USA,Sudmaris,22
3311,2020-06-30,Carne,Granel,C200-300,4140.00,3.15,Ucrania,Sudmaris,27
4718,2020-02-14,Carne,Retail Compensado,C300-500,7000.00,3.50,Francia,Sudmaris,7

In [417]:
sudmaris.PRODUCTO.unique()

array(['Media Concha', 'Carne', 'Entero', 'ENTERO', 'CARNE'], dtype=object)

### LANDES

In [378]:
#Lectura de datos
landes = pd.DataFrame()

for w in weeks:
    try:
        os.chdir(prices+str(year)+'/'+str(w))
    except:
        print('Error al ingresar a', w)
        continue
    w_files = os.listdir(prices+str(year)+'/'+str(w)+'/')
    for file in w_files:
        if 'landes' in file.lower():
            print(file)
            if file[-4:] != '.lnk':
                # Casos XLS
                if file[-4:] in ['.xls','.slk'] :
                    try:
                        df = pd.read_excel(prices+str(year)+'/'+str(w)+'/'+file)
                        
                        #Anexar
                        df['ARCHIVO'] = file
                        landes = landes.append(df)
                        
                    except:
                        print('Error en', file)
                else: # Casos XLSX
                    try: 
                        #Leer hoja donde est√° la tabla
                        wb = load_workbook(filename = prices+str(year)+'/'+str(w)+'/'+file)
                        hoja = wb.sheetnames
                        print(hoja)
                        sheet = wb[hoja[1]]

                        #Transformar hoja en un df
                        
                        df = pd.DataFrame(sheet.values) 
                        df['ARCHIVO'] = file

                        #Anexar
                        landes = sudmaris.append(df)
                    except:
                        print('Error en', file)

DM Landes 2020_11.xls
DM Landes Mussels 2020_10-16.xls
DM Landes 2020_17.xls
Landes Mussels 2020 Data salmon.xls
DM Landes 2020_19.xls
DM Landes 2020_20 y 21.xls
DM Landes 2020_20 y 21.xls
DM Landes 2020_23.xls
DM Landes 2020_25.xls
DM Landes 2020_26.xls
Landes Mussels 2020 Data salmon.xls
DM Landes 2020_28.xls
DM Landes 2020_32.xls
DM Landes 2020_35, 34, 33.xls
DM Landes 2020_36 y 37.xls
DM Landes 2020_38,39,40.xls
DM Landes 2020_45.xls
DM Landes 2020_48.xls
DM Landes 2020_49.xls
DM Landes 2020_50.xls
Landes Mussels 2020_07.xls

In [379]:
landes[landes['Unnamed: 3'].isna() == False].ARCHIVO.unique()

array(['Landes Mussels 2020 Data salmon.xls', 'DM Landes 2020_28.xls',
       'DM Landes 2020_32.xls', 'DM Landes 2020_35, 34, 33.xls',
       'DM Landes 2020_45.xls', 'DM Landes 2020_48.xls',
       'DM Landes 2020_49.xls'], dtype=object)

In [383]:
landes1 = landes.iloc[:,[0,1,2,3,4,5,6,7,8,9,10]]
landes1

,Fecha de Embarque (dd/mm/aaaa),PRODUCTO,EMPAQUE,calibre,Toneladas,PRECIO USD/KG FOB,T7Venta,Pa√≠s,PRECIO USD/KG CFR,Monto de la factura CFR,ARCHIVO
0,2020-01-06,CARNE IQF,GRANEL,200/300,23.0,3.026087,PROGRAMA,ALEMANIA,3.178261,73100.0,DM Landes 2020_11.xls
1,2020-01-09,CARNE IQF,GRANEL,300/500,22.0,2.736364,PROGRAMA,ITALIA,2.895455,63700.0,DM Landes 2020_11.xls
2,2020-01-09,CARNE IQF,BOLSA NO COMPENSADO,300/500,20.0,3.225000,PROGRAMA,FRANCIA,3.400000,68000.0,DM Landes 2020_11.xls
3,2020-01-16,CARNE IQF,GRANEL,300/500,24.0,2.474167,PROGRAMA,ITALIA,2.620000,62880.0,DM Landes 2020_11.xls
4,2020-01-16,CARNE IQF,GRANEL,100/200,25.0,3.282000,PROGRAMA,UCRANIA,3.450000,86250.0,DM Landes 2020_11.xls
...,...,...,...,...,...,...,...,...,...,...,...
30,2020-02-10,CARNE IQF,GRANEL,NaN,24.0,3.254167,NaN,ESPA√ëA,3.400000,81600.0,Landes Mussels 2020_07.xls
31,2020-02-10,CARNE IQF,GRANEL,NaN,24.0,3.304167,NaN,ITALIA,3.450000,82800.0,Landes Mussels 2020_07.xls
32,2020-02-10,CARNE IQF,GRANEL,NaN,21.9,2.566210,NaN,ITALIA,2.726027,59700.0,Landes Mussels 2020_07.xls
33,2020-02-14,CARNE IQF,GRANEL,NaN,23.0,2.817391,NaN,UKRAINE,3.000000,69000.0,Landes Mussels 2020_07.xls
34,2020-02-14,CARNE IQF,GRANEL,NaN,24.0,2.854167,NaN,ESPA√ëA,3.000000,72000.0,Landes Mussels 2020_07.xls

In [384]:
landes2 = landes.loc[:,['ARCHIVO','Fecha',
       'Pais', 'Unnamed: 0', 'ENERO', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']]

In [385]:
landes2.dropna(axis=1, how='all',inplace=True)
landes2.dropna(axis=0, how='all',inplace=True)
landes2

,ARCHIVO,Fecha,Pais,ENERO,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 12
0,DM Landes 2020_11.xls,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DM Landes 2020_11.xls,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DM Landes 2020_11.xls,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DM Landes 2020_11.xls,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DM Landes 2020_11.xls,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,Landes Mussels 2020_07.xls,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Landes Mussels 2020_07.xls,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Landes Mussels 2020_07.xls,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Landes Mussels 2020_07.xls,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Landes Mussels 2020_07.xls,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [386]:
landes2 = landes2.dropna(axis=0, thresh = 4)
landes2.dropna(axis=1, thresh = 10, inplace=True)
landes2

C:\Users\erossel\anaconda3\envs\r-reticulate\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,ARCHIVO,ENERO,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Landes Mussels 2020 Data salmon.xls,Pa√≠s,Fecha de Embarque (dd/mm/aaaa),Monto de la factura CFR,Toneladas,PRECIO USD/KG CFR,PRECIO USD/KG FOB,PRODUCTO,EMPAQUE,calibre,T7Venta
1,Landes Mussels 2020 Data salmon.xls,ALEMANIA,2020-01-06 00:00:00,73100,23,3.17826,3.02609,CARNE IQF,GRANEL,200/300,PROGRAMA
2,Landes Mussels 2020 Data salmon.xls,ITALIA,2020-01-09 00:00:00,63700,22,2.89545,2.73636,CARNE IQF,GRANEL,300/500,PROGRAMA
3,Landes Mussels 2020 Data salmon.xls,FRANCIA,2020-01-09 00:00:00,68000,20,3.4,3.225,CARNE IQF,BOLSA NO COMPENSADO,300/500,PROGRAMA
4,Landes Mussels 2020 Data salmon.xls,ITALIA,2020-01-16 00:00:00,62880,24,2.62,2.47417,CARNE IQF,GRANEL,300/500,PROGRAMA
...,...,...,...,...,...,...,...,...,...,...,...
256,DM Landes 2020_49.xls,ITALIA,2020-11-20 00:00:00,56400,24,2.35,2.225,CARNE IQF,GRANEL,iNDUSTRIAL,SPOT
257,DM Landes 2020_49.xls,ESPA√ëA,2020-11-24 00:00:00,132000,48,2.75,2.625,CARNE IQF,GRANEL,100-200,SPOT
258,DM Landes 2020_49.xls,ROMANIA,2020-11-30 00:00:00,66550,24.5,2.71633,2.53265,CARNE IQF,GRANEL,300-500,SPOT
262,DM Landes 2020_49.xls,FRANCIA,2020-12-03 00:00:00,64904,23.18,2.8,NaN,CARNE IQF,GRANEL,300-500,SPOT
263,DM Landes 2020_49.xls,ESPA√ëA,2020-12-03 00:00:00,55200,24,2.3,NaN,CARNE IQF,GRANEL,INDUSTRIAL,SPOT

In [387]:
landes2.columns = landes2.iloc[0]

In [389]:
landes2

,Landes Mussels 2020 Data salmon.xls,Pa√≠s,Fecha de Embarque (dd/mm/aaaa),Monto de la factura CFR,Toneladas,PRECIO USD/KG CFR,PRECIO USD/KG FOB,PRODUCTO,EMPAQUE,calibre,T7Venta
0,Landes Mussels 2020 Data salmon.xls,Pa√≠s,Fecha de Embarque (dd/mm/aaaa),Monto de la factura CFR,Toneladas,PRECIO USD/KG CFR,PRECIO USD/KG FOB,PRODUCTO,EMPAQUE,calibre,T7Venta
1,Landes Mussels 2020 Data salmon.xls,ALEMANIA,2020-01-06 00:00:00,73100,23,3.17826,3.02609,CARNE IQF,GRANEL,200/300,PROGRAMA
2,Landes Mussels 2020 Data salmon.xls,ITALIA,2020-01-09 00:00:00,63700,22,2.89545,2.73636,CARNE IQF,GRANEL,300/500,PROGRAMA
3,Landes Mussels 2020 Data salmon.xls,FRANCIA,2020-01-09 00:00:00,68000,20,3.4,3.225,CARNE IQF,BOLSA NO COMPENSADO,300/500,PROGRAMA
4,Landes Mussels 2020 Data salmon.xls,ITALIA,2020-01-16 00:00:00,62880,24,2.62,2.47417,CARNE IQF,GRANEL,300/500,PROGRAMA
...,...,...,...,...,...,...,...,...,...,...,...
256,DM Landes 2020_49.xls,ITALIA,2020-11-20 00:00:00,56400,24,2.35,2.225,CARNE IQF,GRANEL,iNDUSTRIAL,SPOT
257,DM Landes 2020_49.xls,ESPA√ëA,2020-11-24 00:00:00,132000,48,2.75,2.625,CARNE IQF,GRANEL,100-200,SPOT
258,DM Landes 2020_49.xls,ROMANIA,2020-11-30 00:00:00,66550,24.5,2.71633,2.53265,CARNE IQF,GRANEL,300-500,SPOT
262,DM Landes 2020_49.xls,FRANCIA,2020-12-03 00:00:00,64904,23.18,2.8,NaN,CARNE IQF,GRANEL,300-500,SPOT
263,DM Landes 2020_49.xls,ESPA√ëA,2020-12-03 00:00:00,55200,24,2.3,NaN,CARNE IQF,GRANEL,INDUSTRIAL,SPOT

In [390]:
landes_f = pd.concat([landes1, landes2], ignore_index=True)

In [391]:
landes_f

,Fecha de Embarque (dd/mm/aaaa),PRODUCTO,EMPAQUE,calibre,Toneladas,PRECIO USD/KG FOB,T7Venta,Pa√≠s,PRECIO USD/KG CFR,Monto de la factura CFR,ARCHIVO,Landes Mussels 2020 Data salmon.xls
0,2020-01-06 00:00:00,CARNE IQF,GRANEL,200/300,23,3.02609,PROGRAMA,ALEMANIA,3.17826,73100,DM Landes 2020_11.xls,NaN
1,2020-01-09 00:00:00,CARNE IQF,GRANEL,300/500,22,2.73636,PROGRAMA,ITALIA,2.89545,63700,DM Landes 2020_11.xls,NaN
2,2020-01-09 00:00:00,CARNE IQF,BOLSA NO COMPENSADO,300/500,20,3.225,PROGRAMA,FRANCIA,3.4,68000,DM Landes 2020_11.xls,NaN
3,2020-01-16 00:00:00,CARNE IQF,GRANEL,300/500,24,2.47417,PROGRAMA,ITALIA,2.62,62880,DM Landes 2020_11.xls,NaN
4,2020-01-16 00:00:00,CARNE IQF,GRANEL,100/200,25,3.282,PROGRAMA,UCRANIA,3.45,86250,DM Landes 2020_11.xls,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
4287,2020-11-20 00:00:00,CARNE IQF,GRANEL,iNDUSTRIAL,24,2.225,SPOT,ITALIA,2.35,56400,NaN,DM Landes 2020_49.xls
4288,2020-11-24 00:00:00,CARNE IQF,GRANEL,100-200,48,2.625,SPOT,ESPA√ëA,2.75,132000,NaN,DM Landes 2020_49.xls
4289,2020-11-30 00:00:00,CARNE IQF,GRANEL,300-500,24.5,2.53265,SPOT,ROMANIA,2.71633,66550,NaN,DM Landes 2020_49.xls
4290,2020-12-03 00:00:00,CARNE IQF,GRANEL,300-500,23.18,NaN,SPOT,FRANCIA,2.8,64904,NaN,DM Landes 2020_49.xls
4291,2020-12-03 00:00:00,CARNE IQF,GRANEL,INDUSTRIAL,24,NaN,SPOT,ESPA√ëA,2.3,55200,NaN,DM Landes 2020_49.xls

In [393]:
landes_f.columns = ['FECHA','PRODUCTO','EMPAQUE','CALIBRE','CANTIDAD','PRECIO FOB', 'TIPO VENTA','PAIS','PRECIO CFR', 'MONTO CFR','ARCHIVO', 'ARCHIVO2']

In [395]:
landes_f.head()

,FECHA,PRODUCTO,EMPAQUE,CALIBRE,CANTIDAD,PRECIO FOB,TIPO VENTA,PAIS,PRECIO CFR,MONTO CFR,ARCHIVO,ARCHIVO2,EMPRESA
0,2020-01-06 00:00:00,CARNE IQF,GRANEL,200/300,23,3.02609,PROGRAMA,ALEMANIA,3.17826,73100,DM Landes 2020_11.xls,NaN,Landes
1,2020-01-09 00:00:00,CARNE IQF,GRANEL,300/500,22,2.73636,PROGRAMA,ITALIA,2.89545,63700,DM Landes 2020_11.xls,NaN,Landes
2,2020-01-09 00:00:00,CARNE IQF,BOLSA NO COMPENSADO,300/500,20,3.225,PROGRAMA,FRANCIA,3.4,68000,DM Landes 2020_11.xls,NaN,Landes
3,2020-01-16 00:00:00,CARNE IQF,GRANEL,300/500,24,2.47417,PROGRAMA,ITALIA,2.62,62880,DM Landes 2020_11.xls,NaN,Landes
4,2020-01-16 00:00:00,CARNE IQF,GRANEL,100/200,25,3.282,PROGRAMA,UCRANIA,3.45,86250,DM Landes 2020_11.xls,NaN,Landes

In [397]:
# Transformaciones de las columnas
landes_f['EMPRESA'] = 'Landes'
landes_f['FECHA'] = landes_f.FECHA.apply(lambda f: pd.to_datetime(f, errors='coerce'))

In [398]:
landes_f[landes_f.FECHA.isna()]

,FECHA,PRODUCTO,EMPAQUE,CALIBRE,CANTIDAD,PRECIO FOB,TIPO VENTA,PAIS,PRECIO CFR,MONTO CFR,ARCHIVO,ARCHIVO2,EMPRESA
50,NaT,CARNE IQF,GRANEL,100/200,25,NaN,PROGRAMA,NaN,3.166,NaN,DM Landes Mussels 2020_10-16.xls,NaN,Landes
51,NaT,CARNE IQF,GRANEL,200/300,25,NaN,PROGRAMA,NaN,2.966,NaN,DM Landes Mussels 2020_10-16.xls,NaN,Landes
52,NaT,CARNE IQF,GRANEL,200/300,25,NaN,PROGRAMA,NaN,2.816,NaN,DM Landes Mussels 2020_10-16.xls,NaN,Landes
53,NaT,CARNE IQF,GRANEL,200/300,25,NaN,PROGRAMA,NaN,2.816,NaN,DM Landes Mussels 2020_10-16.xls,NaN,Landes
54,NaT,CARNE IQF,GRANEL,300/500,25,NaN,PROGRAMA,NaN,2.616,NaN,DM Landes Mussels 2020_10-16.xls,NaN,Landes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3612,NaT,NaN,NaN,NaN,609.2,NaN,NaN,NaN,3092.15,1.88373e+06,NaN,DM Landes 2020_45.xls,Landes
3818,NaT,PRODUCTO,EMPAQUE,calibre,Toneladas,PRECIO USD/KG FOB,T7Venta,Pa√≠s,PRECIO USD/KG CFR,Monto de la factura CFR,NaN,DM Landes 2020_48.xls,Landes
3841,NaT,NaN,NaN,NaN,609.2,NaN,NaN,NaN,3092.15,1.88373e+06,NaN,DM Landes 2020_48.xls,Landes
4054,NaT,PRODUCTO,EMPAQUE,calibre,Toneladas,PRECIO USD/KG FOB,T7Venta,Pa√≠s,PRECIO USD/KG CFR,Monto de la factura CFR,NaN,DM Landes 2020_49.xls,Landes
4077,NaT,NaN,NaN,NaN,609.2,NaN,NaN,NaN,3092.15,1.88373e+06,NaN,DM Landes 2020_49.xls,Landes

In [401]:
landes_f.drop(landes_f.loc[landes_f.FECHA.isna()].index, axis=0, inplace = True)

In [402]:
landes = landes_f.copy()

In [403]:
landes['SEMANA'] = landes.FECHA.apply(lambda f: f.isocalendar()[1])
landes.CALIBRE = landes.CALIBRE.apply(lambda x: str(x).split(" ")[0])
landes.CANTIDAD = landes.CANTIDAD.apply(lambda c: pd.to_numeric(c, errors='coerce'))*1000
landes['PRECIO CFR'] = landes['PRECIO CFR'].apply(lambda c: pd.to_numeric(c, errors='coerce'))
landes['PRECIO FOB'] = landes['PRECIO FOB'].apply(lambda c: pd.to_numeric(c, errors='coerce'))
landes.sort_values(by='FECHA', ascending = True, inplace = True)
landes.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2813 entries, 0 to 2961
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   FECHA       2813 non-null   datetime64[ns]
 1   PRODUCTO    2813 non-null   object
 2   EMPAQUE     2813 non-null   object
 3   CALIBRE     2813 non-null   object
 4   CANTIDAD    2813 non-null   float64
 5   PRECIO FOB  2810 non-null   float64
 6   TIPO VENTA  2778 non-null   object
 7   PAIS        2813 non-null   object
 8   PRECIO CFR  2813 non-null   float64
 9   MONTO CFR   2813 non-null   object
 10  ARCHIVO     1532 non-null   object
 11  ARCHIVO2    1281 non-null   object
 12  EMPRESA     2813 non-null   object
 13  SEMANA      2813 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(1), object(9)
memory usage: 329.6+ KB

In [404]:
landes.drop(['ARCHIVO','ARCHIVO2'], axis=1, inplace= True)
landes.drop_duplicates(inplace= True)

In [405]:
landes.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 268 entries, 0 to 2961
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   FECHA       268 non-null    datetime64[ns]
 1   PRODUCTO    268 non-null    object
 2   EMPAQUE     268 non-null    object
 3   CALIBRE     268 non-null    object
 4   CANTIDAD    268 non-null    float64
 5   PRECIO FOB  265 non-null    float64
 6   TIPO VENTA  235 non-null    object
 7   PAIS        268 non-null    object
 8   PRECIO CFR  268 non-null    float64
 9   MONTO CFR   268 non-null    object
 10  EMPRESA     268 non-null    object
 11  SEMANA      268 non-null    int64
dtypes: datetime64[ns](1), float64(3), int64(1), object(7)
memory usage: 27.2+ KB

In [406]:
landes.sample(20)

,FECHA,PRODUCTO,EMPAQUE,CALIBRE,CANTIDAD,PRECIO FOB,TIPO VENTA,PAIS,PRECIO CFR,MONTO CFR,EMPRESA,SEMANA
3085,2020-04-24,CARNE IQF,GRANEL,200/300,24000.0,2.970833,SPOT,ESPA√ëA,3.150000,75600,Landes,17
2957,2020-12-03,CARNE IQF,GRANEL,INDUSTRIAL,24000.0,2.170000,SPOT,ESPA√ëA,2.300000,55200,Landes,49
2920,2020-10-10,CARNE IQF,GRANEL,300-500,22000.0,2.318182,SPOT,ITALIA,2.500000,55000,Landes,41
917,2020-06-20,CARNE IQF,BOLSA COMPENSADO,200/300,20004.0,3.335043,PROGRAMA,FRANCIA,3.550000,71014.2,Landes,25
2973,2020-01-24,CARNE IQF,GRANEL,nan,50000.0,3.366000,NaN,UCRANIA,3.450000,172500,Landes,4
3466,2020-02-28,CARNE IQF,GRANEL,200/300,24000.0,2.854167,PROGRAMA,ESPA√ëA,3.000000,68500,Landes,9
543,2020-04-25,CARNE IQF,GRANEL,200/300,24000.0,2.850000,PROGRAMA,ITALIA,3.037500,72900,Landes,17
3024,2020-02-06,CARNE IQF,GRANEL,200/300,25000.0,2.982000,PROGRAMA,UKRAINE,3.150000,78750,Landes,6
1929,2020-09-10,CARNE IQF,GRANEL,200-300,23000.0,2.526087,PROGRAMA,FRANCIA,2.700000,62100,Landes,37
4126,2020-04-09,CARNE IQF,GRANEL,300/500,25000.0,2.696000,PROGRAMA,UKRAINE,2.880000,72000,Landes,15
1917,2020-08-20,CARNE IQF,GRANEL,100-200,25000.0,3.200000,PROGRAMA,UKRAINE,3.400000,85000,Landes,34
2987,2020-02-06,CARNE IQF,GRANEL,nan,25000.0,2.982000,NaN,UKRAINE,3.150000,78750,Landes,6
3758,2020-09-03,CARNE IQF,GRANEL,100-200,22000.0,3.018182,SPOT,U.S.A.,3.200000,70400,Landes,36
1837,2020-04-24,CARNE IQF,BOLSA COMPENSADO,300/500,20004.0,3.335043,PROGRAMA,FRANCIA,3.550000,71014.2,Landes,17
1867,2020-06-17,CARNE IQF,GRANEL,100/200,25000.0,3.058000,PROGRAMA,UKRAINE,3.250000,81250,Landes,25
3123,2020-06-26,CARNE IQF,GRANEL,300/500,25000.0,2.600000,PROGRAMA,UKRAINE,2.800000,70000,Landes,26
570,2020-01-16,CARNE IQF,GRANEL,300/500,23000.0,2.622826,PROGRAMA,FRANCIA,2.775000,63825,Landes,3
3559,2020-07-16,CARNE IQF,GRANEL,300/500,24000.0,2.708333,SPOT,ITALIA,2.875000,69000,Landes,29
3721,2020-07-10,CARNE IQF,GRANEL,100/200,25000.0,3.200000,PROGRAMA,UKRAINE,3.400000,85000,Landes,28
2962,2020-01-06,CARNE IQF,GRANEL,nan,23000.0,3.026087,NaN,ALEMANIA,3.178261,73100,Landes,2

In [407]:
landes[landes.duplicated(keep=False)]

Empty DataFrame
Columns: [FECHA, PRODUCTO, EMPAQUE, CALIBRE, CANTIDAD, PRECIO FOB, TIPO VENTA, PAIS, PRECIO CFR, MONTO CFR, EMPRESA, SEMANA]
Index: []

In [416]:
landes.PRODUCTO.unique()

array(['CARNE IQF', 'CARNE IQF & ENTERO'], dtype=object)

# TOTAL 2020

In [810]:
# Fantasma

datamussel = standrews.copy()
datamussel.EMPRESA = 'Data Mussel'
datamussel.CANTIDAD = datamussel.CANTIDAD*np.random.rand(1)[0]
datamussel['PRECIO CFR'] = datamussel['PRECIO CFR']*np.random.rand(1)[0]

In [811]:
datamussel.head()

,FECHA,PRODUCTO,EMPAQUE,CALIBRE,CANTIDAD,PRECIO CFR,TIPO VENTA,PAIS,EMPRESA,SEMANA
0,2020-01-06,CARNE,GRANEL,C200-300,20957.881932,1.602440,SPOT,BIELORRUSIA,Data Mussel,2
1,2020-01-06,ENTERO,SIN SALSA,40-60,16270.442059,1.110657,PROGRAMA,USA,Data Mussel,2
2,2020-01-06,ENTERO,SIN SALSA,E-23-32,14402.065937,1.160388,SPOT,USA,Data Mussel,2
3,2020-01-06,ENTERO,SIN SALSA,E-23-29,15440.052672,1.088554,PROGRAMA,USA,Data Mussel,2
4,2020-01-07,CARNE,RETAIL COMPENSADO,C200-300,3892.450253,2.707572,PROGRAMA,USA,Data Mussel,2

In [812]:
data_mussel_2020 = pd.concat([datamussel, camanchaca, landes, manuelita, standrews, sudmaris], axis=0)

In [813]:
print(camanchaca.shape)
print(landes.shape)
print(manuelita.shape)
print(standrews.shape)
print(sudmaris.shape)
print(camanchaca.shape[0]+landes.shape[0]+manuelita.shape[0]+standrews.shape[0]+ sudmaris.shape[0])

(1483, 10)
(268, 12)
(0, 0)
(1403, 10)
(434, 9)
3588

In [814]:
data_mussel_2020.shape

(4991, 12)

In [815]:
data_mussel_2020

,FECHA,PRODUCTO,EMPAQUE,CALIBRE,CANTIDAD,PRECIO CFR,TIPO VENTA,PAIS,EMPRESA,SEMANA,PRECIO FOB,MONTO CFR
0,2020-01-06,CARNE,GRANEL,C200-300,20957.881932,1.602440,SPOT,BIELORRUSIA,Data Mussel,2,NaN,NaN
1,2020-01-06,ENTERO,SIN SALSA,40-60,16270.442059,1.110657,PROGRAMA,USA,Data Mussel,2,NaN,NaN
2,2020-01-06,ENTERO,SIN SALSA,E-23-32,14402.065937,1.160388,SPOT,USA,Data Mussel,2,NaN,NaN
3,2020-01-06,ENTERO,SIN SALSA,E-23-29,15440.052672,1.088554,PROGRAMA,USA,Data Mussel,2,NaN,NaN
4,2020-01-07,CARNE,RETAIL COMPENSADO,C200-300,3892.450253,2.707572,PROGRAMA,USA,Data Mussel,2,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
8228,2020-12-30,Carne,Granel,200-400,6270.000000,NaN,NaN,Chile,Sudmaris,53,NaN,NaN
8229,2020-12-30,Carne,Granel,300-500,3340.000000,NaN,NaN,Chile,Sudmaris,53,NaN,NaN
8230,2020-12-30,Carne,Granel,200-300,30.000000,NaN,NaN,Chile,Sudmaris,53,NaN,NaN
8219,2020-12-30,Entero,Sin Salsa,40-60,3529.350000,2.100000,NaN,USA,Sudmaris,53,NaN,NaN
8232,2020-12-30,Carne,Granel,300-500,710.000000,NaN,NaN,Chile,Sudmaris,53,NaN,NaN

In [816]:
# Formatos de datos

In [817]:
data_mussel_2020.CANTIDAD = data_mussel_2020.CANTIDAD.apply(lambda c: pd.to_numeric(c, errors='coerce'))

In [818]:
dict_productos = {'ENTERO': 'ENTERO', 'JUGOSON':'ENTERO', 'CARNE':'CARNE', 'MEDIA CONCHA':'MEDIA CONCHA', \
                  'ENTERO IQF':'ENTERO', 'CARNE IQF': 'CARNE','CARNE IQF & ENTERO':'CARNE', 'MEAT':'CARNE', 'WHO':'ENTERO','INDUSTRIAL': 'CARNE'}

data_mussel_2020.PRODUCTO = data_mussel_2020.PRODUCTO.apply(lambda p: dict_productos[p.upper()])
data_mussel_2020.PRODUCTO.unique()

array(['CARNE', 'ENTERO', 'MEDIA CONCHA'], dtype=object)

In [819]:
dict_empaques = {'GRANEL':'GRANEL','RETAIL':'RETAIL NO COMPENSADO',                
'RETAIL COMPENSADO':'RETAIL COMPENSADO',
'RETAIL NO COMPENSADO':'RETAIL NO COMPENSADO',
'SIN SALSA':'SIN SALSA',
'CON SALSA':'CON SALSA',
'CON SALSA CON ESTUCHE':'CON SALSA CON ESTUCHE',
'CON SALSA SIN ESTUCHE':'CON SALSA SIN ESTUCHE',
'SIN SALSA  CON ESTUCHE':'SIN SALSA CON ESTUCHE',
'GRANEL':'GRANEL',
'RETAIL':'RETAIL',
'RETAIL NO COMPENSADO':'RETAIL NO COMPENSADO', 
'SALSA DE MANTEQUILLA':'CON SALSA',
'SIN SALSA':'SIN SALSA',
'CON SALSA CON ESTUCHE':'CON SALSA CON ESTUCHE',
'RETAIL COMPENSADO':'RETAIL COMPENSADO',
'CON SALSA':'CON SALSA',
'BOLSA NO COMPENSADO':'RETAIL NO COMPENSADO',
'BOLSA COMPENSADO':'RETAIL COMPENSADO',
'RETIAL COMPENSADO':'RETAIL COMPENSADO',
'RETIAL NO COMPENSADO':'RETAIL NO COMPENSADO',
'SIN SALSA CON ESTUCHE':'SIN SALSA CON ESTUCHE',
'CON ESTUCHE SIN SALSA': 'SIN SALSA CON ESTUCHE',
'SIN SALSA CON ESTUCHES':'SIN SALSA CON ESTUCHE',
'CON SALSA Y ESTUCHE':'CON SALSA CON ESTUCHE',
'CON ESTUCHE CON SALSA':'CON SALSA CON ESTUCHE',
'FOODSERV':'SIN SALSA',
'CON SALSA Y CON ESTUCHE':'CON SALSA CON ESTUCHE',
'RETAIL COMPENSADO':'RETAIL COMPENSADO',
'MEDIA CONCHA':'MEDIA CONCHA',
'ENTERO':'ENTERO',
'BOLSA SUDMARIS':'RETAIL NO COMPENSADO',
'RETAIL NO COMEPNSADO':'RETAIL NO COMPENSADO',
'BOLSA PANAPESCA':'RETAIL NO COMPENSADO',
'RETAIL  COMPENSADO': 'RETAIL COMPENSADO',
'SIN SAL SA':'SIN SALSA'}

data_mussel_2020.EMPAQUE = data_mussel_2020.EMPAQUE.apply(lambda e: dict_empaques[e.strip().upper()])

In [820]:
data_mussel_2020.EMPAQUE.unique()

array(['GRANEL', 'SIN SALSA', 'RETAIL COMPENSADO', 'CON SALSA',
       'CON SALSA CON ESTUCHE', 'RETAIL NO COMPENSADO',
       'SIN SALSA CON ESTUCHE', 'RETAIL'], dtype=object)

In [821]:
data_mussel_2020.CALIBRE.unique()

array(['C200-300', '40-60', 'E-23-32', 'E-23-29', 'C90-150', 'C300-500',
       'E20-30', 'C100-200', 'E-50-80', '18-27', 'E-50-70', 'MC40-60',
       'MC60-80', 'E-60-80', 'E-40-60', '35-45', 'MC100-120', 'C200-500',
       'E60-80', 'MC80-100', 'SIN', 'E50-70', 'MC20-40', '27-36',
       'C40-100', 'C500-800', 'nan', 'C', 'None', 'C500-1000', '200-300',
       '100-200', '20-35', '60-80', '300-500', '50-70', '500-UP', '44-77',
       '0', '200/300', '300/500', '100/200', 'industrial', '500',
       'INDUSTRIAL', '100-200/200-300/300-500/40-60/60-80',
       '200-300/300-500', '100-200/200-300/300-500', 'iNDUSTRIAL',
       'C60-80', 'C100-120', 'C500-700', 'C80-100', 'C40-60', 'C60-81',
       'C200-400', 'C70-90', '', '23-29', '80-100', '500-700', '100-120',
       'Industrial', '70-90', '200-400'], dtype=object)

In [822]:
numeros = [str(i) for i in range(10)]
numeros

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [823]:
data_mussel_2020.CALIBRE.fillna('SIN')
data_mussel_2020.loc[data_mussel_2020.CALIBRE == '', ['CALIBRE']] = 'SIN'
data_mussel_2020.loc[data_mussel_2020.CALIBRE == '-', ['CALIBRE']] = 'SIN'
data_mussel_2020.loc[data_mussel_2020.CALIBRE == 'C', ['CALIBRE']] = 'SIN'
data_mussel_2020.CALIBRE = data_mussel_2020.CALIBRE.apply(lambda c:'C'+c.strip() if c[0] in numeros else c.strip())
data_mussel_2020.CALIBRE = data_mussel_2020.CALIBRE.apply(lambda c: 'C0' if c.strip().upper().find('IND') != -1 else c.strip().upper())
data_mussel_2020.CALIBRE = data_mussel_2020.CALIBRE.apply(lambda c: c.strip().replace('MC','C').replace('/LB','').replace('E-','E').replace('C-','C'))

In [824]:
data_mussel_2020.CALIBRE.unique()

array(['C200-300', 'C40-60', 'E23-32', 'E23-29', 'C90-150', 'C300-500',
       'E20-30', 'C100-200', 'E50-80', 'C18-27', 'E50-70', 'C60-80',
       'E60-80', 'E40-60', 'C35-45', 'C100-120', 'C200-500', 'C80-100',
       'SIN', 'C20-40', 'C27-36', 'C40-100', 'C500-800', 'NAN', 'NONE',
       'C500-1000', 'C20-35', 'C50-70', 'C500-UP', 'C44-77', 'C0',
       'C200/300', 'C300/500', 'C100/200', 'C500',
       'C100-200/200-300/300-500/40-60/60-80', 'C200-300/300-500',
       'C100-200/200-300/300-500', 'C500-700', 'C60-81', 'C200-400',
       'C70-90', 'C23-29'], dtype=object)

In [825]:
# 
dict_calibre = {
'C90-150':'C200-300',
'C100-120':'C100-200',
'C500-1000':'C500-UP',
'C500-700':'C500-UP',
'C500 UP':'C500-UP',
'500-UP':'C500-UP',
'C500-800':'C500-UP',
'C500-700':'C500-UP',
'C91-136':'C100-200'
}

data_mussel_2020.CALIBRE = data_mussel_2020.CALIBRE.apply(lambda c: dict_calibre[c] if c in dict_calibre.keys() else c)

In [826]:
data_mussel_2020['MES'] = data_mussel_2020['FECHA'].dt.month
data_mussel_2020['A√ëO'] = data_mussel_2020['FECHA'].dt.year

In [827]:
data_mussel_2020.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4991 entries, 0 to 8232
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   FECHA       4991 non-null   datetime64[ns]
 1   PRODUCTO    4991 non-null   object
 2   EMPAQUE     4991 non-null   object
 3   CALIBRE     4991 non-null   object
 4   CANTIDAD    4991 non-null   float64
 5   PRECIO CFR  4837 non-null   float64
 6   TIPO VENTA  3222 non-null   object
 7   PAIS        4987 non-null   object
 8   EMPRESA     4991 non-null   object
 9   SEMANA      4991 non-null   int64
 10  PRECIO FOB  265 non-null    float64
 11  MONTO CFR   268 non-null    object
 12  MES         4991 non-null   int64
 13  A√ëO         4991 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(3), object(7)
memory usage: 584.9+ KB

In [828]:
factor_peso = 1

In [829]:
data_mussel_2020.loc[:,['CANTIDAD']] = data_mussel_2020['CANTIDAD']/factor_peso

In [830]:
data_mussel_2020.drop(data_mussel_2020[data_mussel_2020.PAIS.isna()].index, axis=0, inplace=True)

In [831]:
data_mussel_2020.PAIS = data_mussel_2020.PAIS.apply(lambda p: p.capitalize().strip().\
                                                      replace('√≥','o').replace('√∫','u').replace('√≠','i').\
                                                      replace('√©','e').replace('√°','a'))

In [832]:
data_mussel_2020.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4985 entries, 0 to 8232
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   FECHA       4985 non-null   datetime64[ns]
 1   PRODUCTO    4985 non-null   object
 2   EMPAQUE     4985 non-null   object
 3   CALIBRE     4985 non-null   object
 4   CANTIDAD    4985 non-null   float64
 5   PRECIO CFR  4831 non-null   float64
 6   TIPO VENTA  3218 non-null   object
 7   PAIS        4985 non-null   object
 8   EMPRESA     4985 non-null   object
 9   SEMANA      4985 non-null   int64
 10  PRECIO FOB  265 non-null    float64
 11  MONTO CFR   268 non-null    object
 12  MES         4985 non-null   int64
 13  A√ëO         4985 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(3), object(7)
memory usage: 584.2+ KB

In [833]:
# Paises y mercados
paises_mercados = pd.read_excel('/Users/erossel/Dropbox/Salmon Derivates/Datamussel/Data mensual y semanal/Procesamiento/BBDD Paises-Mercados.xlsx')

for col in paises_mercados.columns:
    paises_mercados[col] = paises_mercados[col].apply(lambda p: p.capitalize().strip().\
                                                      replace('√≥','o').replace('√∫','u').replace('√≠','i').\
                                                      replace('√©','e').replace('√°','a'))

paises_mercados.sample(10)

        PAIS  MERCADO    Mercados 2 Mercados Carne Mercados Entero
13   Ucrania      Uee     Otros uee            Uee       Otros uee
18  Lituania      Uee     Otros uee            Uee       Otros uee
37   Ukraine      Uee     Otros uee            Uee       Otros uee
85    Latvia   Europa     Otros uee   Otros europa       Otros uee
31   Holland   Europa  Otros europa   Otros europa    Otros europa
63   Estonia      Uee     Otros uee            Uee       Otros uee
33    Mexico  America       America        America         America
42    Canada  America       America        America         America
14   Belgica   Europa  Otros europa   Otros europa    Otros europa
54    Sweden   Europa  Otros europa   Otros europa    Otros europa

In [834]:
paises_mercados.drop_duplicates(inplace=True)

In [835]:
paises_mercados.shape

(85, 5)

In [836]:
data_mussel_2020 = data_mussel_2020.merge(paises_mercados, how='left', left_on='PAIS', right_on='PAIS')

In [837]:
data_mussel_2020.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4985 entries, 0 to 4984
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   FECHA            4985 non-null   datetime64[ns]
 1   PRODUCTO         4985 non-null   object
 2   EMPAQUE          4985 non-null   object
 3   CALIBRE          4985 non-null   object
 4   CANTIDAD         4985 non-null   float64
 5   PRECIO CFR       4831 non-null   float64
 6   TIPO VENTA       3218 non-null   object
 7   PAIS             4985 non-null   object
 8   EMPRESA          4985 non-null   object
 9   SEMANA           4985 non-null   int64
 10  PRECIO FOB       265 non-null    float64
 11  MONTO CFR        268 non-null    object
 12  MES              4985 non-null   int64
 13  A√ëO              4985 non-null   int64
 14  MERCADO          4970 non-null   object
 15  Mercados 2       4970 non-null   object
 16  Mercados Carne   4970 non-null   object
 17  Mercados Entero  4970 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(3), object(11)
memory usage: 740.0+ KB

In [838]:
# Paises y mercados

In [839]:
data_mussel_2020.head()

,FECHA,PRODUCTO,EMPAQUE,CALIBRE,CANTIDAD,PRECIO CFR,TIPO VENTA,PAIS,EMPRESA,SEMANA,PRECIO FOB,MONTO CFR,MES,A√ëO,MERCADO,Mercados 2,Mercados Carne,Mercados Entero
0,2020-01-06,CARNE,GRANEL,C200-300,20957.881932,1.602440,SPOT,Bielorrusia,Data Mussel,2,NaN,NaN,1,2020,Uee,Otros uee,Uee,Otros uee
1,2020-01-06,ENTERO,SIN SALSA,C40-60,16270.442059,1.110657,PROGRAMA,Usa,Data Mussel,2,NaN,NaN,1,2020,America,America,America,America
2,2020-01-06,ENTERO,SIN SALSA,E23-32,14402.065937,1.160388,SPOT,Usa,Data Mussel,2,NaN,NaN,1,2020,America,America,America,America
3,2020-01-06,ENTERO,SIN SALSA,E23-29,15440.052672,1.088554,PROGRAMA,Usa,Data Mussel,2,NaN,NaN,1,2020,America,America,America,America
4,2020-01-07,CARNE,RETAIL COMPENSADO,C200-300,3892.450253,2.707572,PROGRAMA,Usa,Data Mussel,2,NaN,NaN,1,2020,America,America,America,America

In [840]:
# Producto Equivalente
dict_producto_equivalente = {
'ENTEROSIN SALSA':'ENTERO SIN SALSA',
'ENTEROCON SALSA':'ENTERO CON SALSA',
'ENTEROCON SALSA CON ESTUCHE':'ENTERO CON SALSA',
'ENTEROSIN SALSA CON ESTUCHE':'ENTERO SIN SALSA',
'CARNEGRANEL':'CARNE GRANEL',
'CARNERETAIL':'CARNE RETAIL',
'CARNERETAIL NO COMPENSADO':'CARNE RETAIL',
'CARNERETAIL COMPENSADO':'CARNE RETAIL'
}

data_mussel_2020['PRODUCTO EQUIVALENTE'] = (data_mussel_2020.PRODUCTO.apply(str.strip)+data_mussel_2020.EMPAQUE.apply(str.strip)).apply(lambda e: dict_producto_equivalente[e.strip().upper()] if e.strip().upper() in dict_producto_equivalente.keys() else '')

In [841]:
data_mussel_2020['PRODUCTO_EMPAQUE'] = data_mussel_2020.PRODUCTO.apply(str.strip)+data_mussel_2020.EMPAQUE.apply(str.strip)

In [842]:
# An√°lisis s√≥lo precio CFR
data_mussel_2020.drop(['PRECIO FOB'], axis=1, inplace=True)

In [843]:
#C√°lculo del precio equivalente
factores = pd.read_excel('/Users/erossel/Dropbox/Salmon Derivates/Datamussel/Data mensual y semanal/Procesamiento/BBDD Factores.xlsx', sheet_name='H2')
factores.fillna(0, inplace=True)
factores

,A,B,PRODUCTO_EMPAQUE,ALFA,BETA,PRODUCTO EQUIVALENTE
0,ENTERO,SIN SALSA,ENTEROSIN SALSA,0.0,0.0,ENTERO SIN SALSA
1,ENTERO,CON SALSA,ENTEROCON SALSA,0.0,0.0,ENTERO CON SALSA
2,ENTERO,CON SALSA CON ESTUCHE,ENTEROCON SALSA CON ESTUCHE,0.3,0.0,ENTERO CON SALSA
3,ENTERO,SIN SALSA CON ESTUCHE,ENTEROSIN SALSA CON ESTUCHE,0.3,0.0,ENTERO SIN SALSA
4,CARNE,GRANEL,CARNEGRANEL,0.0,0.0,CARNE GRANEL
5,CARNE,RETAIL,CARNERETAIL,0.0,0.0,CARNE RETAIL
6,CARNE,RETAIL NO COMPENSADO,CARNERETAIL NO COMPENSADO,0.0,0.0,CARNE RETAIL
7,CARNE,RETAIL COMPENSADO,CARNERETAIL COMPENSADO,0.0,0.1,CARNE RETAIL

In [844]:
data_mussel_2020 = data_mussel_2020.merge(factores[['PRODUCTO_EMPAQUE','ALFA','BETA']], how='left', on='PRODUCTO_EMPAQUE')

In [845]:
data_mussel_2020.ALFA.value_counts()

0.0    4307
0.3     128
Name: ALFA, dtype: int64

In [846]:
data_mussel_2020.BETA.value_counts()

0.0    4074
0.1     361
Name: BETA, dtype: int64

In [847]:
data_mussel_2020.head()

,FECHA,PRODUCTO,EMPAQUE,CALIBRE,CANTIDAD,PRECIO CFR,TIPO VENTA,PAIS,EMPRESA,SEMANA,...,MES,A√ëO,MERCADO,Mercados 2,Mercados Carne,Mercados Entero,PRODUCTO EQUIVALENTE,PRODUCTO_EMPAQUE,ALFA,BETA
0,2020-01-06,CARNE,GRANEL,C200-300,20957.881932,1.602440,SPOT,Bielorrusia,Data Mussel,2,...,1,2020,Uee,Otros uee,Uee,Otros uee,CARNE GRANEL,CARNEGRANEL,0.0,0.0
1,2020-01-06,ENTERO,SIN SALSA,C40-60,16270.442059,1.110657,PROGRAMA,Usa,Data Mussel,2,...,1,2020,America,America,America,America,ENTERO SIN SALSA,ENTEROSIN SALSA,0.0,0.0
2,2020-01-06,ENTERO,SIN SALSA,E23-32,14402.065937,1.160388,SPOT,Usa,Data Mussel,2,...,1,2020,America,America,America,America,ENTERO SIN SALSA,ENTEROSIN SALSA,0.0,0.0
3,2020-01-06,ENTERO,SIN SALSA,E23-29,15440.052672,1.088554,PROGRAMA,Usa,Data Mussel,2,...,1,2020,America,America,America,America,ENTERO SIN SALSA,ENTEROSIN SALSA,0.0,0.0
4,2020-01-07,CARNE,RETAIL COMPENSADO,C200-300,3892.450253,2.707572,PROGRAMA,Usa,Data Mussel,2,...,1,2020,America,America,America,America,CARNE RETAIL,CARNERETAIL COMPENSADO,0.0,0.1

In [848]:
data_mussel_2020['PRECIO EQUIV.'] = (data_mussel_2020['PRECIO CFR']-data_mussel_2020.ALFA)*(1-data_mussel_2020.BETA)

In [849]:
data_mussel_2020['P*Q'] = data_mussel_2020['CANTIDAD']*data_mussel_2020['PRECIO EQUIV.']

In [850]:
data_mussel_2020['ANTIGIO'] = (data_mussel_2020['PRECIO CFR']-data_mussel_2020.ALFA)/(1 - data_mussel_2020.BETA)

In [851]:
data_mussel_2020['PRECIO EQUIV.'].unique()

array([1.60244044, 1.11065699, 1.1603879 , ..., 1.93      , 1.81      ,
       2.02643172])

In [852]:
data_mussel_2020.to_csv('/Users/erossel/Dropbox/Salmon Derivates/Datamussel/Data mensual y semanal/Procesamiento/data_mussel_2020.csv',encoding='utf-8')

In [853]:
data_mussel_2020.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4985 entries, 0 to 4984
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   FECHA                 4985 non-null   datetime64[ns]
 1   PRODUCTO              4985 non-null   object
 2   EMPAQUE               4985 non-null   object
 3   CALIBRE               4985 non-null   object
 4   CANTIDAD              4985 non-null   float64
 5   PRECIO CFR            4831 non-null   float64
 6   TIPO VENTA            3218 non-null   object
 7   PAIS                  4985 non-null   object
 8   EMPRESA               4985 non-null   object
 9   SEMANA                4985 non-null   int64
 10  MONTO CFR             268 non-null    object
 11  MES                   4985 non-null   int64
 12  A√ëO                   4985 non-null   int64
 13  MERCADO               4970 non-null   object
 14  Mercados 2            4970 non-null   object
 15  Mercados Carne        4970 non-null   object
 16  Mercados Entero       4970 non-null   object
 17  PRODUCTO EQUIVALENTE  4985 non-null   object
 18  PRODUCTO_EMPAQUE      4985 non-null   object
 19  ALFA                  4435 non-null   float64
 20  BETA                  4435 non-null   float64
 21  PRECIO EQUIV.         4300 non-null   float64
 22  P*Q                   4300 non-null   float64
 23  ANTIGIO               4300 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(3), object(13)
memory usage: 973.6+ KB

In [857]:
df2021 = pd.read_csv('/Users/erossel/Dropbox/Salmon Derivates/Datamussel/Data mensual y semanal/Procesamiento/data_mussel_2021.csv')

In [1]:
consolidado_precios = pd.concat([data_mussel_2020, df2021], ignore_index=True)

NameError: name 'pd' is not defined

In [5]:
df20_21.to_csv('/Users/erossel/Dropbox/Salmon Derivates/Datamussel/Data mensual y semanal/Procesamiento/data_mussel_consolidado_precios.csv',encoding='utf-8',index=False)

In [2]:
import pandas as pd
df20_21 = pd.read_csv('/Users/erossel/Dropbox/Salmon Derivates/Datamussel/Data mensual y semanal/Procesamiento/data_mussel_consolidado_precios.csv')
df20_21.head()

,FECHA,PRODUCTO,EMPAQUE,CALIBRE,CANTIDAD,PRECIO CFR,TIPO VENTA,PAIS,EMPRESA,SEMANA,...,Mercados 2,Mercados Carne,Mercados Entero,PRODUCTO EQUIVALENTE,PRODUCTO_EMPAQUE,ALFA,BETA,PRECIO EQUIV.,P*Q,ANTIGIO
0,1/6/2020 0:00,CARNE,GRANEL,C200-300,"20,957.88",1.60,SPOT,Bielorrusia,Data Mussel,2,...,Otros uee,Uee,Otros uee,CARNE GRANEL,CARNEGRANEL,0.0,0.0,1.602440,33583.757450,1.602440
1,1/6/2020 0:00,ENTERO,SIN SALSA,C40-60,"16,270.44",1.11,PROGRAMA,Usa,Data Mussel,2,...,America,America,America,ENTERO SIN SALSA,ENTEROSIN SALSA,0.0,0.0,1.110657,18070.880230,1.110657
2,1/6/2020 0:00,ENTERO,SIN SALSA,E23-32,"14,402.07",1.16,SPOT,Usa,Data Mussel,2,...,America,America,America,ENTERO SIN SALSA,ENTEROSIN SALSA,0.0,0.0,1.160388,16711.983070,1.160388
3,1/6/2020 0:00,ENTERO,SIN SALSA,E23-29,"15,440.05",1.09,PROGRAMA,Usa,Data Mussel,2,...,America,America,America,ENTERO SIN SALSA,ENTEROSIN SALSA,0.0,0.0,1.088554,16807.336730,1.088554
4,1/7/2020 0:00,CARNE,RETAIL COMPENSADO,C200-300,"3,892.45",2.71,PROGRAMA,Usa,Data Mussel,2,...,America,America,America,CARNE RETAIL,CARNERETAIL COMPENSADO,0.0,0.1,2.436815,9485.179581,3.008413

In [3]:
df20_21.CANTIDAD = df20_21.CANTIDAD.apply(lambda v: pd.to_numeric(v, errors='coerce'))
df20_21['PRECIO CFR'] = df20_21['PRECIO CFR'].apply(lambda v: pd.to_numeric(v, errors='coerce'))
df20_21['PRECIO EQUIV.']= df20_21['PRECIO EQUIV.'].apply(lambda v: pd.to_numeric(v, errors='coerce'))

In [4]:
list(df20_21.columns)

['FECHA',
 'PRODUCTO',
 'EMPAQUE',
 'CALIBRE',
 'CANTIDAD',
 'PRECIO CFR',
 'TIPO VENTA',
 'PAIS',
 'EMPRESA',
 'SEMANA',
 'MONTO CFR',
 'MES',
 'Ano',
 'MERCADO',
 'Mercados 2',
 'Mercados Carne',
 'Mercados Entero',
 'PRODUCTO EQUIVALENTE',
 'PRODUCTO_EMPAQUE',
 'ALFA',
 'BETA',
 'PRECIO EQUIV.',
 'P*Q',
 'ANTIGIO']